import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const read = name => JSON.parse(readFileSync(new URL(`../../ai_docs/games/recom/${name}.json`, import.meta.url))).records;
const entries = [];
const sources = r => [...new Set([...(r.sources || []), r.source, r.supportingSource].filter(Boolean))];
const add = (r, extra) => entries.push({ id: r.id, name: r.name, category: 'cards', campaign: r.campaign || 'sora', summary: '', checkable: true, collectible: false, sources: sources(r), ...extra });
for (const r of read('attack-cards')) add(r, { id: r.id.replace('recom-', 'recom-sora-'), family: 'attack', summary: r.acquisition, instructions: r.acquisition, stats: [['Strike', String(r.strike)], ['Thrust', String(r.thrust)], ['Finish', String(r.finish)], ['Element', r.element]], uncertainty: 'CP varies by card value. A verified per-value CP table is not yet available.' });
for (const r of read('other-cards')) add(r, { id: r.id.replace('recom-', 'recom-sora-'), family: r.family, summary: r.acquisition, instructions: r.acquisition, uncertainty: r.permanentDeckInventory ? undefined : 'A battle pickup. Recording discovery does not add permanent deck stock.' });
for (const r of read('enemy-cards')) {
 const farm = read('enemy-card-farms').find(f => f.enemy === r.name);
 add(r, { family: 'enemy', summary: `${r.ability}${r.duration ? ` · ${r.duration}` : ''}`, stats: [['Ability', r.ability], ['Duration', r.duration || 'See card effect'], ...(r.campaign === 'sora' ? [['CP', r.cp === undefined || r.cp === null ? 'Unresolved' : String(r.cp)]] : [])], instructions: farm && r.campaign === 'sora' ? `${farm.selectionRule} Found in ${farm.worldsSourceText.replace(/\[\s*\d+\s*\]/g, '')}.` : 'Refer to the linked sources for the campaign encounter. Detailed boss-event acquisition mapping is still being checked.', drops: farm && r.campaign === 'sora' ? [{enemy: r.name, rate: `${farm.basePercent}% base${farm.boostedPercent ? ` · ${farm.boostedPercent}% in ${farm.boostRooms.join(', ')}` : ''}`, location: farm.specialRoom || farm.worldsSourceText}] : undefined, uncertainty: r.campaign === 'sora' && (r.cp === undefined || r.cp === null) ? 'Published CP values conflict. No cost is assigned here.' : undefined, sources: [...sources(r), ...(farm ? [farm.source] : [])] });
}
for (const r of read('map-cards')) for (const campaign of r.campaigns) add(r, { id: r.id.replace('recom-', `recom-${campaign}-`), campaign, family: 'map', summary: `${({red:'Encounter',green:'Battle condition',blue:'Service',key:'Story / reward key',joker:'Joker'})[r.family] || r.family} card.`, stats: [['Card group', r.family]], instructions: ['Teeming Darkness','Almighty Darkness','Looming Darkness'].includes(r.name) ? 'Eligible enemy-card drops are boosted by 2.5×. Defeat the intended enemy last. Mushroom cards use their own rules.' : r.name === 'Key to Rewards' ? 'Opens a Room of Rewards when the world door requirements are met. Base and Days bonus chests are separate rewards.' : 'Room cards are used when creating or opening rooms. Track discovery here; held numeric values and copies are separate from this check.', uncertainty: 'Exact world/difficulty drop tables and all door requirements remain under review.' });
for (const [name, family, summary] of [['Soul Eater','battle','Riku’s attack card. World decks have fixed numeric card values.'],['The King','battle','Riku’s friend card; a battle pickup rather than editable deck stock.']]) add({id:`recom-riku-card-${name.toLowerCase().replaceAll(' ','-')}`,name,campaign:'riku',source:name==='Soul Eater'?'https://www.khwiki.com/Soul_Eater':'https://www.khwiki.com/Friend_Card'}, {family,summary,uncertainty:'Battle Cards coverage is partial. The native HD index shows five entries; two are documented here.'});
for (const r of read('sleights')) add(r, {category:'sleights',family:r.family,summary:r.combinationReference,instructions:r.combinationReference,prerequisites:r.acquisition,collectible:false,stats:[['Use',r.normalCombat===false?'Mini-game only':'Combat']]});
for (const r of read('worlds-and-rewards')) add(r, {name:r.reward,category:'rewards',family:r.method,world:r.world,summary:r.method==='room-of-rewards-base'?'Room of Rewards · base chest':r.method==='room-of-rewards-days'?'Room of Rewards · Days bonus chest':'Bounty reward',instructions:`${r.world}: ${r.method.replaceAll('-',' ')}. ${r.prerequisite || ''}`,prerequisites:r.prerequisite,collectible:true,uncertainty:'Exact door card costs and repeat-reward rules have not been independently verified.'});
for (const r of read('riku-decks')) add(r, {name:r.world,category:'decks',world:r.world,checkable:false,summary:`${r.cardsInSourceOrder.length} cards in this world preset.`,instructions:r.scopeNote,cards:r.cardsInSourceOrder,uncertainty:'World preset reference; retained boss cards are additional. Corridor and boss substitutions are not included.'});
for (const r of read('moogle-packs')) add(r, {name:`${r.tier} ${r.kind[0].toUpperCase()+r.kind.slice(1)} Pack`,category:'shop',checkable:false,summary:`${r.priceMooglePoints} Moogle Points · 5 random cards`,stats:[['Price',`${r.priceMooglePoints} MP`],['Floors',r.floorRange.join('–')],['Cards','5']],instructions:'Packs contain random cards, not a guaranteed named card or value. A newly generated shop gives a free Attack Pack: Grass on floors 1–6 and Brown on floors 7–13.',uncertainty:'Pack probabilities and stock quantities are not yet documented.'});
for (const r of read('steam-achievements')) add(r, {category:'achievements',campaign:r.campaignScope==='run'?'shared':r.campaignScope,summary:r.requirement,instructions:r.requirement,uncertainty:r.campaignScope==='run'?'Shared run reference. Check manually against your in-game achievement; card or chest checks do not certify run restrictions.':undefined});
const mini=[['monstro-belly-brawl',"Monstro’s Belly Brawl",'Monstro','Complete the Shadow-clearing event.','',null,'Recorded in the Journal without a numeric score in the inspected HD screen.'],['balloon-glider','Balloon Glider','100 Acre Wood','500+ points','points',500,'First clear: Firaga Burst. Second clear: Stop 0. Preserve balloons and collect honey.'],['whirlwind-plunge','Whirlwind Plunge','100 Acre Wood','2,000+ points','points',2000,'First clear: Mega-Ether 5. Second clear: Gravity 9. Collect honey and recover Pooh after collisions.'],['bumble-rumble','Bumble-Rumble','100 Acre Wood','70 bees within 100 seconds','seconds',100,'First clear: Elixir 1. Second clear: Hi-Potion 7. Protect Pooh’s honey; the achievement has a separate 70-bee condition.'],['tiggers-jump-a-thon',"Tigger’s Jump-a-Thon",'100 Acre Wood','120+ points','points',120,'First clear: Idyll Romp. Second clear: Ether 9. Repeat the stump sequence.'],['veggie-panic','Veggie Panic','100 Acre Wood','150+ points','points',150,'First clear: Cross-slash+. Second clear: Fire 8. Sort cabbage left and pumpkins right.']];
for (const [slug,name,world,summary,unit,target,instructions] of mini) add({id:`recom-sora-minigame-${slug}`,name,sources:['https://www.khwiki.com/Game:100_Acre_Wood','https://steamcommunity.com/stats/2552430/achievements/']},{category:'minigames',world,summary,unit,target,instructions});
const worlds=read('worlds');
const result={entries,worlds,coverage:'HD Re:Chain of Memories reference: both campaigns, card discoveries, 41 world rewards, sleights, six Mini-games, 12 Riku world decks, Moogle packs and Steam goals. Card coverage is partial: World/Gimmick and all Riku Battle Card entries are not yet reconciled. Counts describe this guide, not the native 100% requirement. CP conflicts remain unresolved.'};
if(new Set(entries.map(e=>e.id)).size!==entries.length)throw new Error('Duplicate CoM IDs');
mkdirSync(new URL('../../src/games/recom/',import.meta.url),{recursive:true});
writeFileSync(new URL('../../src/games/recom/ui-data.json',import.meta.url),JSON.stringify(result,null,2)+'\n');
console.log(`Re:CoM: ${entries.length} sourced guide entries.`);
