import type { GameGuide, CollectionEntry } from './types';
import content from './kh3/content.json';

const worlds = [
  ['Olympus','Return with the Gummiphone for Lucky Emblems. Five Golden Herc Figures exchange for Hero’s Belt in Agora.'],
  ['Twilight Town','Tram Common contains the Bistrot, Moogle workshop and Classic Kingdom posters.'],
  ['Toy Box','Galaxy Toys spans several floors and departments; use area names to distinguish repeated rooms.'],
  ['Kingdom of Corona','Complete Rapunzel’s four Forest Clasp activities before reaching the Shore; sources disagree on the later cutoff.'],
  ['Monstropolis','Return after the story for elevator/vault treasures and the Vault Passage emblem.'],
  ['Arendelle','Frozen Slider’s ten prizes are separate from the 25 world chests. The score achievement needs 600,000, above the 500,000 A rank.'],
  ['The Caribbean','Island treasures, underwater passages and Port Royal are separate areas. Ship combat is distinct from Gummi combat.'],
  ['San Fransokyo','Choose day or night at the save point; Lucky Emblem 3 requires night.'],
  ['100 Acre Wood','Three Lucky Emblems; no numbered base-game chests.'],
  ['Keyblade Graveyard','Battlegate 0 differs from the post-clear gates. Dark Inferno awards Crystal Regalia.'],
  ['The Final World','Return for the Orichalcum+ chest.'],
  ['Scala ad Caelum','The nine listed chests belong to Re Mind and do not count toward the base 245.'],
  ['Starlight Way','Gummi zone containing Olympus, Twilight Town, Toy Box and Corona routes.'],
  ['Misty Stream','Schwarzgeist requires a ship with at least 200 Speed.'],
  ['The Eclipse','Clear the five other battles to unlock Omega Machina and its Orichalcum+.'],
  ['Limitcut','Clear the eleven initial data battles to unlock Xion and Master Xehanort.'],
  ['Secret Episode','All thirteen data wins unlock Yozora. Victory rewards Crystal Regalia+.'],
];
const guide: GameGuide = {
  id:'kh3', name:'Kingdom Hearts III', edition:'Re Mind · Steam', accent:'#536bba',
  craftingLabel:'Synthesis & Cooking',
  worlds:worlds.map(([name,summary])=>({name,summary})),
  categories:[
    {id:'treasures',label:'Treasures',icon:'chest'},
    {id:'emblems',label:'Lucky Emblems',icon:'heart'},
    {id:'photos',label:'Photo Missions',icon:'search'},
    {id:'keyblades',label:'Keyblades & Equipment',icon:'sword'},
    {id:'ingredients',label:'Ingredients',icon:'leaf'},
    {id:'cuisine',label:'Excellent Cuisine',icon:'cup'},
    {id:'classic-kingdom',label:'Classic Kingdom',icon:'book'},
    {id:'classic-records',label:'Classic Kingdom Scores',icon:'medal'},
    {id:'challenges',label:'Challenges & Minigames',icon:'spark'},
    {id:'herc',label:'Golden Herc Figures',icon:'world'},
    {id:'battlegates',label:'Battlegates',icon:'monster'},
    {id:'reports',label:'Secret Reports',icon:'scroll'},
    {id:'gummi',label:'Gummi Routes',icon:'world'},
    {id:'remind-treasures',label:'Re Mind Treasures',icon:'chest'},
    {id:'remind',label:'Limitcut & Secret Episode',icon:'sword'},
    {id:'achievements',label:'Steam Achievements',icon:'medal'},
    {id:'material',label:'Materials',icon:'flask'},
    {id:'equipment',label:'Armor, Accessories & Party Weapons',icon:'book'},
    {id:'party-equipment',label:'Temporary Party Equipment',icon:'book'},
    {id:'platform-keyblades',label:'Other Platform Keyblades',icon:'book'},
    {id:'synthesis-history',label:'Synthesis History',icon:'book'},
    {id:'collector-goals',label:'Collector Goals',icon:'book'},
    {id:'rewards',label:'Reward Milestones',icon:'book'},
    {id:'adversaries',label:'Adversaries',icon:'book'},
    {id:'game-records',label:'Game Records',icon:'book'},
    {id:'slider-prizes',label:'Frozen Slider Prizes',icon:'book'},
    {id:'cuisine-reference',label:'Cooking & Meal Effects',icon:'book'},
    {id:'material-reference',label:'Material Farming Rules',icon:'book'},
    {id:'gummi-missions',label:'Gummi Missions',icon:'book'},
    {id:'gummi-battles',label:'Gummi Battles',icon:'book'},
    {id:'gummi-treasures',label:'Gummi Treasures',icon:'book'},
    {id:'gummi-spheres',label:'Treasure Spheres',icon:'book'},
    {id:'gummi-fragments',label:'Blueprint Fragments',icon:'book'},
    {id:'gummi-parts',label:'Gummi Parts & Cosmetics',icon:'book'},
    {id:'gummi-blueprints',label:'Gummi Blueprints',icon:'book'},
    {id:'gummi-abilities',label:'Gummi Abilities',icon:'book'},
    {id:'gummi-reference',label:'Gummi Building',icon:'book'},
    {id:'premium-codes',label:'Premium Codes',icon:'book'},
    {id:'premium-merits',label:'EZ Merits',icon:'book'},
    {id:'premium-reference',label:'PRO Ranks',icon:'book'},
    {id:'pro-bosses',label:'PRO Boss Scores',icon:'book'},
    {id:'edition-reference',label:'Editions & Save Rules',icon:'book'},
    {id:'naval',label:'Leviathan & Naval Progress',icon:'book'},
    {id:'naval-rewards',label:'Naval Rewards',icon:'book'},
  ],
  entries:content.entries as CollectionEntry[], recipes:content.recipes,
  coverage:'Updated Steam/Re Mind: 245 base chests, 90 emblems, nine DLC chests, 10 Slider prizes, 20 Photo Missions, 88 synthesis recipes, 170 forge actions, 28 cooking recipes, 172 ingredient route groups across all 59 ingredients, 81 adversaries, 54 Game Records, 23 Classic scores, 46 Gummi missions, 33 Gummi battles, nine sphere marker routes, 45 blueprint fragments, 13 Special Weapon references, 374 parts/cosmetics, 52 blueprints and 51 Steam achievements. Earliest chest/emblem access, every ingredient/material alternative, medal roll probabilities and platform/code predicates remain partial. Forest Clasp cutoff, Flan score equality and PRO rank B remain disputed. Categories use their own units; reference-only entries are not collection goals. Data Jiminy is excluded.',
};
export default guide;
