const stage=document.querySelector('#stage'),status=document.querySelector('#status'),toggle=document.querySelector('#toggle-3d'),motion=document.querySelector('#motion');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let selected='terra',scene,loading,enabled=!reduced.matches&&!navigator.connection?.saveData;
motion.checked=!reduced.matches;
function preview(name){selected=name;document.querySelectorAll('[data-character]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.character===name)));document.querySelector('#fallback').src=`/assets/bbs-journal/${name}-stage.jpg`;stage.setAttribute('aria-label',`${name[0].toUpperCase()+name.slice(1)} preview on the Wayfinder Station`);const link=document.querySelector('#open-journal');link.href=`http://127.0.0.1:4173/#/bbsfm/contents?character=${name[0].toUpperCase()+name.slice(1)}`;link.textContent=`Open ${name[0].toUpperCase()+name.slice(1)}’s Reports ›`;scene?.select(name,motion.checked);}
for(const b of document.querySelectorAll('[data-character]')){for(const event of ['pointerenter','focus','click'])b.addEventListener(event,()=>preview(b.dataset.character));}
async function load(){if(scene){scene.setEnabled(enabled);stage.classList.toggle('loaded',enabled);return}if(!enabled||loading)return;status.textContent='Loading the station and characters…';loading=(async()=>{try{const {createScene}=await import('./scene.js');scene=await createScene(document.querySelector('#canvas-mount'),document.querySelector('#metrics'));scene.select(selected,false);scene.setEnabled(enabled);stage.classList.toggle('loaded',enabled);status.textContent='Hover, focus or tap to bring a character forward.';}catch(error){enabled=false;stage.classList.remove('loaded');status.textContent='3D could not load. Character stills remain available.';console.error(error);}finally{loading=null;sync()}})();await loading;}
function sync(){toggle.textContent=enabled?'Use still images':'Try 3D scene';motion.disabled=!enabled;if(!enabled){stage.classList.remove('loaded');if(!status.textContent.startsWith('3D could'))status.textContent=reduced.matches?'Reduced motion: character stills. 3D is optional.':'Character stills. 3D is optional.';}scene?.setEnabled(enabled);}
toggle.addEventListener('click',()=>{enabled=!enabled;sync();void load()});motion.addEventListener('change',()=>scene?.select(selected,false));reduced.addEventListener('change',()=>{motion.checked=!reduced.matches;if(reduced.matches){enabled=false;sync()}});
sync();if(enabled){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();void load()}},{rootMargin:'80px'});observer.observe(stage)}
