import { bbsData, finishCondition } from '../games/bbsModel';
import { BbsModal } from './BbsControls';
export function BbsFinishChart({character,selected,checks,onSelect,onClose}:{character:string;selected:string;checks:Record<string,boolean>;onSelect:(id:string)=>void;onClose:()=>void}) {
 const rows=bbsData.finish.filter(r=>r.character===character);
 const positions=new Map<string,{x:number;y:number}>();
 for(let level=1;level<=6;level++)rows.filter(r=>r.level===level).forEach((r,i)=>positions.set(r.name,{x:12+(level-1)*176,y:42+i*94}));
 const height=50+Math.max(...[1,2,3,4,5,6].map(l=>rows.filter(r=>r.level===l).length))*94;
 return <BbsModal title={`${character} · Finish Commands`} onClose={onClose}><p className="bbs-chart-help">Choose a finisher to read its prerequisites and unlock conditions.</p><div className="bbs-chart-scroll" role="region" aria-label="Finish Command tree"><div className="bbs-finish-tree" style={{width:1060,height}}><svg width="1060" height={height} aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="3">{rows.flatMap(r=>r.parents.map(p=>{const a=positions.get(p),b=positions.get(r.name);return a&&b?<path key={r.id+p} d={`M${a.x+152},${a.y+23} H${b.x-10} V${b.y+23} H${b.x}`}/>:null;}))}</g></svg>{[1,2,3,4,5,6].map(l=><span className="bbs-chart-level" style={{left:12+(l-1)*176}} key={l}>LEVEL {l}</span>)}{rows.map(r=>{const p=positions.get(r.name)!;return <button key={r.id} style={{left:p.x,top:p.y}} className={`bbs-finish-node ${checks[r.id]?'acquired':''}`} aria-current={selected===r.id?'true':undefined} aria-label={`${r.name}${checks[r.id]?', acquired':''}. ${r.parents.length?'Requires '+r.parents.join(' or ')+'. ':''}${finishCondition(r)}`} onClick={()=>onSelect(r.id)}><span>{r.name}</span><span aria-hidden="true">{checks[r.id]?'✓':'›'}</span></button>})}</div></div><p className="bbs-small">Each branch requires an eligible preceding finisher to be equipped. Progress is separate for {character}.</p></BbsModal>;
}
