import {TreasureBoard} from './TreasureBoard';
import {hasTreasureBoard} from '../games/treasureModel';
import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import type { CollectionEntry, GameGuide } from '../games/types';
import { type GuideProfile, addTargets } from '../games/profile';
import { entryTitle } from '../domain/entryPresentation';
import { bbsCharacters, bbsData, bbsHref, bbsId, checkableEntries, finishCondition, inBbsScope, mainCharacter, normalizeScope, scopedText, validScope, type BbsCharacter } from '../games/bbsModel';
import { BbsFinishChart } from './BbsFinishChart';
import { BbsMelding, type BbsUpdate } from './BbsMelding';
import { BbsQuantity, CharacterPills } from './BbsControls';
import { useIndexCapacity } from './useIndexCapacity';
import crystalSources from '../games/bbsfm/crystal-sources.json';
import './bbs-journal.css';
const asset=`${import.meta.env.BASE_URL}assets/bbs-journal/`;
const decode=(s:string)=>{try{return decodeURIComponent(s)}catch{return s}};
const chapterNames:Record<string,string>={worlds:'Browse by World',treasures:'Treasures',stickers:'Stickers',album:'Sticker Album Rewards',reports:'Secret Reports',keyblades:'Keyblades',commands:'Command Collection',styles:'Command Styles',dlinks:'D-Links',abilities:'Abilities',finishers:'Finish Commands',arena:'Mirage Arena',challenges:'Unversed Missions',minigames:'Minigames',bestiary:'The Unversed',icecream:'Ice Cream Guide',achievements:'Steam Achievements',materials:'Inventory & Materials',plan:'Farming Plan',search:'Search',progress:'Save & Settings',episodes:'Episode Collection'};
const chapters=['worlds','treasures','stickers','album','reports','keyblades','commands','styles','dlinks','abilities','finishers','arena','challenges','minigames','icecream'];
export function BbsJournal({guide,route,profile,ready,error,notice,updateNotice,update,toggle,progressPage,retry,character:storedCharacter,onCharacter}:{guide:GameGuide;route:string;profile:GuideProfile;ready:boolean;error:string;notice:string;updateNotice:ReactNode;update:BbsUpdate;toggle:(id:string)=>void;progressPage:ReactNode;retry:()=>void;character:string;onCharacter:(c:string)=>void}) {
 const [path,query='']=route.split('?'),parts=path.split('/');
 const params=new URLSearchParams(query);
 let section=parts[1]||'home';
 if(section==='workshop')section=parts[2]==='plan'?'plan':parts[2]==='materials'?'materials':'melding';
 const requested=params.get('character');
 const scope=requested&&validScope(requested)?requested:validScope(storedCharacter)?storedCharacter:'Terra';
 const character=mainCharacter(scope);
 const episode=scope.includes('Episode');
 const [preview,setPreview]=useState<BbsCharacter>(character),[chart,setChart]=useState(false),[leaf,setLeaf]=useState<'index'|'details'>('index'),[draft,setDraft]=useState(params.get('q')||''),[help,setHelp]=useState('Choose a story or a shared guide.');
 const main=useRef<HTMLElement>(null);
 const selectedId=params.get('entry')||params.get('item')||'';
 const world=section==='worlds'&&parts[2]?decode(parts.slice(2).join('/')):params.get('world')||'';
 const q=params.get('q')||'',status=params.get('status')||'';
 const contents=section==='contents',home=section==='home',final=section==='final',melding=section==='melding';
 const worldList=section==='worlds'&&!world,worldCover=section==='worlds'&&!!world;
 const title=home?'SELECT A CHARACTER':melding?'COMMAND MELDING':final?'FINAL CHAPTER':contents?`${character}’s Reports`:worldCover?world:chapterNames[section]||'Reports';
 const known=home||contents||final||melding||worldList||worldCover||!!chapterNames[section];
 const entries=guide.entries;
 const treasureMode=hasTreasureBoard(guide.id,route);
 const byId=new Map(entries.map(e=>[e.id,e]));
 const scoped=entries.filter(e=>inBbsScope(e,scope));
 const count=(es:CollectionEntry[])=>{const c=checkableEntries(es).filter(e=>e.category!=='treasures'||e.collectible!==false);return `${c.filter(e=>profile.checks[e.id]).length} / ${c.length}`};
 const worldCollectibles=(w:string)=>scoped.filter(e=>e.world===w&&e.collectible&&e.checkable!==false);
 function href(destination:string,more:Record<string,string|undefined>={}){return bbsHref(destination,{character:scope,...more})}
 function changed(changes:Record<string,string>,destination=section){const next=Object.fromEntries(params);Object.entries(changes).forEach(([k,v])=>v?next[k]=v:delete next[k]);return bbsHref(destination,{...next,character:scope});}
 const scopeHref=(c:string)=>bbsHref(section==='contents'?'contents':section==='episodes'?'contents':section,{...Object.fromEntries(params),character:c,entry:undefined,page:undefined,world:undefined});
 function chooseCharacter(c:BbsCharacter){onCharacter(c);location.hash=scopeHref(c);}
 function openEntry(e:CollectionEntry){const dest=e.category==='materials'?'materials':e.category;location.hash=bbsHref(dest,{character:normalizeScope(e.character)||scope,entry:e.id});}
 useEffect(()=>{if(requested&&validScope(requested)&&requested!==storedCharacter)onCharacter(requested)},[requested,storedCharacter,onCharacter]);
 useEffect(()=>{setDraft(q);setLeaf(selectedId?'details':'index');setHelp(melding?'Choose a command, crystal or ability.':contents?'Choose a section of this character’s Reports.':home?'Choose a story or a shared guide.':'Select a record to read its details.');document.title=`${title} · Birth by Sleep`;},[route]);
 const {ref:indexRef,capacity}=useIndexCapacity(`${section}:${scope}:${world}:${q}:${status}`,42);
 const recipes=section==='icecream'?(guide.recipes||[]).filter(r=>r.group==='Ice cream'&&r.character===character):[];
 const materialView=section==='plan'||section==='materials';
 const candidates=section==='episodes'?scoped.filter(e=>['episodes','treasures','keyblades'].includes(e.category)):materialView?scoped.filter(e=>e.category==='materials'&&(section!=='plan'||(profile.targets[e.id]||0)>0)):section==='search'?scoped.filter(e=>e.category!=='materials'):scoped.filter(e=>e.category===section||e.categories?.includes(section));
 const matches=(e:CollectionEntry)=> (!world||world==='all'||e.world===world)&&(!q||`${e.name} ${e.world||''} ${e.area||''} ${e.summary}`.toLowerCase().includes(q.toLowerCase()))&&(!status||(status==='done'?!!profile.checks[e.id]:!profile.checks[e.id]));
 const matching=candidates.filter(matches).sort((a,b)=> (a.order??9999)-(b.order??9999)||a.name.localeCompare(b.name));
 const matchingRecipes=recipes.filter(r=>(!q||r.name.toLowerCase().includes(q.toLowerCase()))&&(!status||(status==='done'?!!profile.checks[r.id]:!profile.checks[r.id])));
 const ids=section==='icecream'?matchingRecipes.map(r=>r.id):matching.map(e=>e.id);
 const pages=Math.max(1,Math.ceil(ids.length/capacity));
 const requestedIndex=ids.indexOf(selectedId);
 const page=Math.max(0,Math.min(pages-1,requestedIndex>=0?Math.floor(requestedIndex/capacity):Number(params.get('page'))||0));
 const shown=ids.slice(page*capacity,(page+1)*capacity);
 const selected=shown.includes(selectedId)?selectedId:shown[0];
 const record=selected?byId.get(selected):undefined;
 const recipe=matchingRecipes.find(r=>r.id===selected);
 const finisher=bbsData.finish.find(r=>r.id===selected);
 const back=home?'#/':contents||final?bbsHref('home'):episode?bbsHref('final'):href('contents');
 function recordCheck(e:CollectionEntry){return e.checkable!==false&&e.category!=='materials'?<label className="bbs-record-check"><input type="checkbox" aria-label={`Complete ${e.name}${e.character?` (${normalizeScope(e.character)})`:''}`} checked={!!profile.checks[e.id]} disabled={!ready} onChange={()=>toggle(e.id)}/>Acquired</label>:null}
 function saveQuantity(field:'owned'|'targets',id:string,value:number|undefined){return update(p=>{const values={...p[field]};if(value===undefined)delete values[id];else values[id]=value;return {...p,[field]:values}})}
 function details(e:CollectionEntry){return <><p>{e.summary}</p>{e.world&&<dl><dt>Location</dt><dd>{e.world}{e.area?` · ${scopedText(e.area,scope)}`:''}</dd></dl>}{e.prerequisites&&<dl><dt>Requires</dt><dd>{e.prerequisites}</dd></dl>}{e.instructions&&e.instructions!==e.summary&&<p>{e.instructions}</p>}{e.reward&&<dl><dt>Reward</dt><dd>{scopedText(e.reward,scope)}</dd></dl>}{e.missability&&<p>{e.missability}</p>}{e.uncertainty&&<p className="bbs-content-note">{e.uncertainty}</p>}{e.category==='bestiary'&&<><h3>Known drops and locations</h3>{crystalSources.filter(s=>s.enemy===e.name).map(s=><section className="bbs-enemy-drop" key={s.crystal}><a href={bbsHref('melding',{character,tab:'crystals',item:s.crystal})}>{s.crystal} ›</a><p>{s.rate}</p><p>{s.locations.map(l=>l.world).join(' · ')}</p><p className="bbs-small">{s.conditions}</p></section>)}</>}{e.drops?.map((d,i)=><p key={i}><strong>{d.enemy}</strong> · {d.location}<br/>{d.details||d.rate}</p>)}{['commands','abilities'].includes(e.category)&&<a className="bbs-page-link" href={bbsHref('melding',{character,tab:e.category==='abilities'?'abilities':'commands',item:e.name})}>Open in Command Melding ›</a>}</>}
 const headerTools=<nav className="bbs-outer-tools" aria-label="Journal tools"><a href={href('search')}>Search</a><a href={href('progress')}>Save & Settings</a></nav>;
 return <div className={`bbs-native bbs-theme-${character.toLowerCase()} bbs-screen-${section} bbs-leaf-${leaf}`} style={{'--bbs-character':melding?'#146fce':{Terra:'#c17a25',Ventus:'#259a58',Aqua:'#2585ce'}[character]} as CSSProperties}>
 <a className="skip-link" href="#bbs-main" onClick={e=>{e.preventDefault();main.current?.focus()}}>Skip to BBS content</a><div className="bbs-outer"><a href="#/">‹ Games</a><span>BIRTH BY SLEEP · FINAL MIX</span>{headerTools}</div>
 <section className="bbs-volume" aria-label="Birth by Sleep journal"><header className="bbs-header"><h1>{home?'SELECT A CHARACTER':melding?'MENU':final?'FINAL CHAPTER':'REPORTS'}</h1>{!home&&<nav className="bbs-location" aria-label="Journal location"><a href={bbsHref('home')}>Home</a>{!melding&&!final&&<a href={back}>{episode?'Final Chapter':character}</a>}<span aria-current="page">{title}</span></nav>}{!home&&!final&&<CharacterPills value={character} onChange={chooseCharacter}/>}</header>{updateNotice}{error&&<div className="bbs-error" role="alert">{error}<button onClick={retry}>Retry loading saved progress</button></div>}
 <main id="bbs-main" ref={main} tabIndex={-1} className="bbs-main">
 {treasureMode?<div className="bbs-paper bbs-reading treasure-host"><div className="bbs-binder" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><TreasureBoard game={guide.id} route={params.has('character')?route:`${route}${query?'&':'?'}character=${encodeURIComponent(scope)}`} entries={entries} checks={profile.checks} ready={ready} save={(id,value,expected)=>update(p=>{if(expected!==undefined&&!!p.checks[id]!==expected)throw new Error('This treasure changed in another tab. Undo was not applied.');return {...p,checks:{...p.checks,[id]:value}};})} renderDetails={e=>details(byId.get(e.id)!)}/></div>:home?<div className="bbs-home"><nav className="bbs-home-menu" aria-label="Stories and shared guides">{bbsCharacters.map(c=><a key={c} className={`bbs-story bbs-story-${c.toLowerCase()} ${preview===c?'previewing':''}`} href={bbsHref('contents',{character:c})} onPointerEnter={()=>setPreview(c)} onFocus={()=>setPreview(c)}><img src={`${asset}${c.toLowerCase()}-portrait.jpg`} alt=""/><strong>{c}</strong></a>)}<a className="bbs-story bbs-final-story" href={bbsHref('final')}><img src={`${asset}aqua-portrait.jpg`} alt=""/><strong>Final Chapter</strong></a><nav className="bbs-home-utilities" aria-label="Shared guides">{[['melding','Command Melding'],['bestiary','Bestiary'],['arena','Mirage Arena'],['challenges','Unversed Missions'],['achievements','Achievements']].map(([id,label])=><a key={id} href={href(id)}>{label}</a>)}</nav></nav><div className="bbs-stage" data-character={preview}><img src={`${asset}${preview.toLowerCase()}-stage.jpg`} alt={`${preview} character preview`}/></div></div>
 :melding?<BbsMelding key={`${character}`} guide={guide} character={character} params={params} profile={profile} ready={ready} update={update} toggle={toggle} onOpenEntry={openEntry}/>
 :contents?<div className="bbs-contents-book"><div className="bbs-binder" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><div className="bbs-portrait"><img src={`${asset}${character.toLowerCase()}-portrait.jpg`} alt={character}/><h2>{character.toUpperCase()}</h2></div><nav className="bbs-contents-list" aria-label={`${character} Reports sections`}>{chapters.map(c=><a key={c} href={href(c)} onMouseEnter={()=>setHelp(`Browse ${chapterNames[c].toLowerCase()} for ${character}.`)} onFocus={()=>setHelp(`Browse ${chapterNames[c].toLowerCase()} for ${character}.`)}><span>{chapterNames[c]}</span>{!['worlds','icecream'].includes(c)&&<small>{count(scoped.filter(e=>e.category===c||e.categories?.includes(c)))}</small>}</a>)}<a href={href('bestiary')}>The Unversed <small>›</small></a></nav></div>
 :final?<div className="bbs-paper bbs-episode-home"><div className="bbs-binder" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><h2>Final Chapter</h2><p>Aqua’s concluding episodes have their own collection records.</p>{['Final Episode','Secret Episode'].map(ep=><a className="bbs-episode-card" key={ep} href={bbsHref('episodes',{character:`Aqua · ${ep}`})}><strong>{ep}</strong><span>{ep==='Final Episode'?'Brightcrest · Episode requirements':'Realm of Darkness · Eight treasure chests · Master’s Defender'}</span><em>Open Reports ›</em></a>)}</div>
 :worldList||worldCover?<div className="bbs-paper bbs-worlds"><div className="bbs-binder" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><h2>{worldCover?world:'Browse by World'}</h2><nav className="bbs-world-list">{worldList?guide.worlds.filter(w=>scoped.some(e=>e.world===w.name)).map(w=><a key={w.name} href={href(`worlds/${encodeURIComponent(w.name)}`)}><span>{w.name}</span><small>{count(worldCollectibles(w.name))}</small></a>):chapters.filter(c=>scoped.some(e=>e.world===world&&(e.category===c||e.categories?.includes(c)))).map(c=><a key={c} href={href(c,{world})}><span>{chapterNames[c]}</span><small>{count(scoped.filter(e=>e.world===world&&(e.category===c||e.categories?.includes(c))))}</small></a>)}</nav>{worldCover&&<a href={href('worlds')}>‹ All worlds</a>}</div>
 :section==='progress'?<div className="bbs-paper bbs-settings">{progressPage}</div>
 :!known?<div className="bbs-paper"><h2>Page not found</h2><a href={bbsHref('home')}>Return to BBS home</a></div>
 :<><nav className="bbs-leaf-switch" aria-label="Book panels"><button aria-pressed={leaf==='index'} onClick={()=>setLeaf('index')}>Index</button><button aria-pressed={leaf==='details'} onClick={()=>setLeaf('details')}>Details</button></nav><div className="bbs-paper bbs-reading"><div className="bbs-binder" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><section className="bbs-index-leaf" aria-label={`${title} index`}><h2>{title}</h2><div className="bbs-collection-count">{section==='icecream'?`${recipes.filter(r=>profile.checks[r.id]).length} / ${recipes.length}`:count(candidates.filter(e=>!world||e.world===world))} {materialView?'materials':'recorded'}</div>{section==='episodes'&&<nav className="bbs-episode-tabs" aria-label="Episode">{['Final Episode','Secret Episode'].map(ep=><a key={ep} href={bbsHref('episodes',{character:`Aqua · ${ep}`})} aria-current={scope===`Aqua · ${ep}`?'page':undefined}>{ep}</a>)}</nav>}
 <form className="bbs-book-filters" onSubmit={e=>{e.preventDefault();location.hash=changed({q:draft,entry:'',page:''})}}><label>Find an entry<input type="search" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button>Find</button>{!episode&&!['finishers','abilities','keyblades','bestiary','icecream','plan','materials','achievements'].includes(section)&&<label>World<select value={world} onChange={e=>{location.hash=changed({world:e.target.value,entry:'',page:''})}}><option value="">All worlds</option>{[...new Set(candidates.flatMap(e=>e.world?[e.world]:[]))].map(w=><option key={w}>{w}</option>)}</select></label>}{!materialView&&section!=='bestiary'&&<label>Show<select value={status} onChange={e=>{location.hash=changed({status:e.target.value,entry:'',page:''})}}><option value="">All entries</option><option value="remaining">Remaining</option><option value="done">Completed</option></select></label>}</form>
 <nav className="bbs-record-list" ref={indexRef} aria-label={`${title} records`}>{shown.map(id=>{const e=byId.get(id),r=matchingRecipes.find(r=>r.id===id),name=e?entryTitle(e):r?.name||'';return <div className="bbs-record-row" key={id}><a href={changed({entry:id})} aria-current={id===selected?'true':undefined}><span>{name}{e?.area&&<small>{scopedText(e.area,scope)}</small>}{!world&&e?.world&&<small>{e.world}</small>}</span></a>{!materialView&&e?.checkable!==false&&<input type="checkbox" aria-label={`Complete ${name} (${scope})`} checked={!!profile.checks[id]} disabled={!ready} onChange={()=>toggle(id)}/>}</div>})}</nav>{!shown.length&&<p className="bbs-empty">{section==='plan'?'Your farming plan is empty for this character.':'No matching records.'}</p>}<nav className="bbs-pagination" aria-label="Record pages"><a aria-label="Previous page" aria-disabled={page===0} tabIndex={page===0?-1:undefined} href={page>0?changed({page:String(page-1),entry:''}):undefined}>◀</a><span>{page+1} / {pages}</span><a aria-label="Next page" aria-disabled={page+1===pages} tabIndex={page+1===pages?-1:undefined} href={page+1<pages?changed({page:String(page+1),entry:''}):undefined}>▶</a></nav></section>
 <article className="bbs-detail-leaf" aria-label="Record details">{!ready?<p>Opening your saved records…</p>:finisher?<><p className="bbs-kicker">{character} · Level {finisher.level}</p><h2>{finisher.name}</h2>{record&&recordCheck(record)}<div className="bbs-detail-scroll"><h3>Prerequisite finishers</h3>{finisher.parents.length?<p>{finisher.parents.map((p,i)=><span key={p}>{i>0?' or ':''}<a href={changed({entry:bbsId(character,'finish',p),q:'',status:''})}>{p}</a></span>)} must be equipped.</p>:<p>None.</p>}<h3>Unlock condition</h3><p>{finishCondition(finisher)}</p>{finisher.parents.length>0&&<p>Progress counts while an eligible prerequisite finisher is equipped.</p>}</div><button className="bbs-view-chart" onClick={()=>setChart(true)}>View chart ↗</button></>:recipe?<><p className="bbs-kicker">{character} · Ice Cream Guide</p><h2>{recipe.name}</h2><label className="bbs-record-check"><input type="checkbox" checked={!!profile.checks[recipe.id]} onChange={()=>toggle(recipe.id)}/>Made</label><div className="bbs-detail-scroll"><p>{recipe.instructions}</p><h3>Ingredients</h3>{recipe.ingredients.map(i=><div className="bbs-ingredient" key={i.id}><a href={href('materials',{entry:i.id})}>{byId.get(i.id)?.name||i.id}</a><span>{profile.owned[i.id]??'?'} / {i.quantity}</span></div>)}<button className="bbs-page-action" onClick={()=>void update(p=>addTargets(p,recipe.ingredients))}>Add ingredients to farming plan</button><a className="bbs-page-link" href={href('plan')}>Open farming plan ›</a></div></>:record?<><p className="bbs-kicker">{normalizeScope(record.character)||'Shared reference'}{record.world?` · ${record.world}`:''}</p><h2>{entryTitle(record)}</h2>{recordCheck(record)}{materialView&&<div className="bbs-stock"><BbsQuantity key={record.id+'owned'} label={`Owned ${record.name}`} value={profile.owned[record.id]} disabled={!ready} save={n=>saveQuantity('owned',record.id,n)}/>{section==='plan'&&<BbsQuantity key={record.id+'target'} label={`Target ${record.name}`} value={profile.targets[record.id]} disabled={!ready} save={n=>saveQuantity('targets',record.id,n)}/>}</div>}<div className="bbs-detail-scroll">{materialView&&section==='plan'&&<p>Remaining: {profile.owned[record.id]===undefined?'Unknown':Math.max(0,(profile.targets[record.id]||0)-profile.owned[record.id])}</p>}{details(record)}{materialView&&<><button className="bbs-page-action" disabled={!ready} onClick={()=>void update(p=>{const targets={...p.targets};if(section==='plan')delete targets[record.id];else targets[record.id]=targets[record.id]||1;return {...p,targets}})}>{section==='plan'?'Remove from farming plan':'Add to farming plan'}</button><a className="bbs-page-link" href={href('plan')}>Open farming plan ›</a></>}</div></>:<p>Select a record from the index.</p>}</article></div></>}
 </main><footer className="bbs-footer"><a href={back}>‹ {home?'Games':'Back'}</a><span>{help}</span>{!home&&<a href={bbsHref('home')}>Home</a>}</footer></section><div className="bbs-save-status" role="status">{error?'Progress needs attention':notice||(!ready?'Opening saved progress…':'Progress saved on this device')}</div>{chart&&<BbsFinishChart character={character} selected={selected||''} checks={profile.checks} onClose={()=>setChart(false)} onSelect={id=>{setChart(false);location.hash=changed({entry:id,q:'',status:''})}}/>}</div>;
}
